# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: im_sync 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "im_sync"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = "2014-04-08"
  s.description = "immat\u{e9}riel.fr sync tools"
  s.email = "jboulnois@immateriel.fr"
  s.executables = ["ask.rb", "onix2imml.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "bin/ask.rb",
    "bin/onix2imml.rb",
    "lib/ask.rb",
    "lib/onix2imml.rb"
  ]
  s.homepage = "http://github.com/immateriel/im_sync"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "immat\u{e9}riel.fr sync tools"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<imml>, [">= 0"])
      s.add_runtime_dependency(%q<im_onix>, [">= 0"])
    else
      s.add_dependency(%q<imml>, [">= 0"])
      s.add_dependency(%q<im_onix>, [">= 0"])
    end
  else
    s.add_dependency(%q<imml>, [">= 0"])
    s.add_dependency(%q<im_onix>, [">= 0"])
  end
end

